LoyolaHouse/LoyolaHouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('Users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('loyola/', include('LoyolaSystem.urls')),

    path('', lambda request: redirect('users:login')),
]

LoyolaHouse/Users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('register-jesuit', views.register_view, name='newAccount'),
    path('<int:user_id>/edit-profile', views.editprofile_view, name='editAccount'),
    path('<int:user_id>/add-viber', views.addviber_view, name='addViber'),
    path('my-profile', views.profile_view, name='myAccount'),
    path('<int:user_id>/<str:viber_id>/delete-viber', views.deleteViber, name='removeViber'),
    path('<int:user_id>/delete-user', views.deleteUser, name='removeUser'),
]

LoyolaHouse/Users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class roles(models.Model):
    role_id = models.AutoField(primary_key=True)
    role_desc = models.CharField(max_length=200)

    def __str__(self):
        return self.role_desc

class UserRole(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role_id = models.IntegerField()

LoyolaHouse/Users/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.views.decorators.cache import never_cache
from .models import roles, UserRole
from django.contrib.auth.models import User
from LoyolaSystem.models import ViberContact

# Create your views here.
@never_cache
def login_view(request):
    if request.user.is_authenticated:
        return redirect('loyola:dashboard')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('loyola:dashboard')
        else:
            messages.error(request, "Wrong Username and Password. Try Again...")
            return redirect('users:login')

    return render(request, 'users/login.html')

@login_required
def register_view(request):
    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')
        password1 = request.POST.get('password1')

        if password != password1:
            messages.error(request, "Password Mismatch")
            return redirect('users:newAccount')
        
        first_name = request.POST.get('FName')
        last_name = request.POST.get('LName')
        contact = request.POST.get('contact')
        role = request.POST.get('role')

        selected_role = roles.objects.get(role_id=role)
        
        if not User.objects.filter(username=username).exists():
            is_superuser = False
            is_staff = False
            is_active = True

            if selected_role.role_desc.lower() == 'admin':
                is_superuser = True
                is_staff = True
            elif selected_role.role_desc.lower() == 'regular':
                is_active = False

            user = User.objects.create_user(
                username = username,
                password = password,
                first_name = first_name,
                last_name = last_name,
                email = username,
                is_superuser = is_superuser,
                is_staff = is_staff,
                is_active = is_active
            )
            user.save()

            ViberContact.objects.create(
                user = user,
                name = f"{first_name} {last_name}",
                viber_id = contact
            )

            UserRole.objects.create(
                user = user,
                role_id = role
            )
        
            messages.success(request, 'New Jesuit has been registered to Loyola System')
            return redirect('users:newAccount')
        
        else:
            messages.error(request,'Jesuit has already been registered')
            return redirect('users:newAccount')

    Roles = roles.objects.all()
    return render(request, 'users/register.html', {
        'roles': Roles,
    })

@login_required
def editprofile_view(request, user_id):
    user = User.objects.get(id=user_id)
    currentrole = UserRole.objects.get(user=user_id)


    if request.method == "POST" and request.POST.get('_method') == 'PATCH':
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.email = request.POST.get('email')
        role = request.POST.get('role')

        currentrole.role_id = role
        currentrole.save()

        selected_role = roles.objects.get(role_id=role)

        user.is_superuser = False
        user.is_staff = False
        user.is_active = True
        
        if selected_role.role_desc.lower() == "admin":
            user.is_superuser = True
            user.is_staff = True 
        elif selected_role.role_desc.lower() == "regular":
            user.is_active = False

        user.save()

        return redirect('loyola:profiles')

    contacts = ViberContact.objects.filter(user=user)
    Roles = roles.objects.all()
    return render(request, 'users/editprofile.html', {
            'user': user, 
            'contacts': contacts,
            'roles': Roles,
            'currentrole': currentrole
        })

def addviber_view(request, user_id):
    if request.method == 'POST':

        user = User.objects.get(id=user_id)
        name = f"{user.first_name} {user.last_name}",
        viber_id = request.POST.get('contact')

        ViberContact.objects.create(
            user = user,
            name = name,
            viber_id = viber_id
        )

    return render(request, 'users/addViber.html')

def profile_view(request):
    return render(request, 'users/myprofile.html')

def deleteViber(request, viber_id, user_id):
    ViberContact.objects.filter(viber_id=viber_id).delete()
    messages.success(request, "Viber contact deleted successfully.")

    return redirect('users:editAccount', user_id=user_id)

def deleteUser(request, user_id):
    User.objects.filter(id=user_id).delete()
    messages.success(request, "Jesuit Account deleted successfully.")

    return redirect('loyola:profiles')

LoyolaHouse/Users/templates/users/addviber.html
{% extends "dashboard.html" %}
{% block content %}
{% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} text-center">{{ message }}</div>
{% endfor %}
{% endif %}
<div class="container mt-4">
    <h2>Add Viber Contact</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group mb-3">
            <label for="contact">Viber</label>
            <input type="tel" class="form-control" name="contact" id="contact" required 
                maxlength="11" minlength="11" value="09" pattern="[0-9]{11}"
                onkeypress="return event.charCode >= 48 && event.charCode <= 57">
        </div>
        <button type="submit" class="btn btn-primary">Add Viber</button>
    </form>
</div>
{% endblock %}

LoyolaHouse/Users/templates/users/editprofile.html
{% extends "dashboard.html" %}
{% block content %}
{% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} text-center">{{ message }}</div>
{% endfor %}
{% endif %}
<form action="{% url 'users:editAccount' user.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="_method" value="PATCH">

    <!-- User Info -->

    <div class="form-outline mb-4">
        <label class="form-label" for="role">User Role</label>
        <select name="role" id="role" value="{{ currentrole.role_id }}">
            {% for role in roles %}
                <option value="{{ role.role_id }}" 
                    {% if role.role_id == currentrole.role_id %} selected {% endif %}>
                    {{ role.role_desc }}
                </option>
            {% endfor %}
        </select>
      </div>

    <div class="mb-3">
        <label for="first_name" class="form-label">First Name</label>
        <input type="text" name="first_name" class="form-control" value="{{ user.first_name }}" required>
    </div>

    <div class="mb-3">
        <label for="last_name" class="form-label">Last Name</label>
        <input type="text" name="last_name" class="form-control" value="{{ user.last_name }}" required>
    </div>

    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" name="email" class="form-control" value="{{ user.email }}" required>
    </div>


    <!-- Viber Contacts -->
    <label class="form-label">Viber Contacts</label>
    <div id="viber-contact-fields">
        {% for contact in contacts %}
            <div class="mb-2 input-group">
                <input type="text" class="form-control" value="{{ contact.viber_id }}" disabled>
                <a href="{% url 'users:removeViber' user.id contact.viber_id %}"><button type="button">Delete</button></a>
            </div>
        {% endfor %}
    </div>

    <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
</form>

{% endblock content %}

LoyolaHouse/Users/templates/users/forgotpw.html
{% extends "index.html" %}
{% block title %} Forgot Password {% endblock %}

{% block form %} 
<form action="{% url 'users:forgot' %}" method="POST">
    {% csrf_token %}
    <div class="form-outline mb-4">
        <label class="form-label" for="email">Email</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Email" required/>
    </div>

    <div class="text-center pt-1 mb-3 pb-1">
        <button class="btn btn-custom btn-block fa-lg mb-2" type="submit">Change Password</button>
    </div>
</form>
{% endblock %}
<!--<div class="text-center">
    <a class="text-muted" href="{% url 'users:login' %}">Log In</a>
</div> -->

LoyolaHouse/Users/templates/users/login.html
{% extends 'index.html' %}
{% block title %} User Log-in Page {% endblock %}

{% block form %} 
  <form action="{% url 'users:login' %}" method='POST'>
    {% csrf_token %}
      <div class="form-outline mb-4">
        <label class="form-label" for="username">Username</label>
        <input type="text" id="username" name='username' class="form-control" placeholder="Username" required/>
      </div>
    
      <div class="form-outline mb-4">
        <label class="form-label" for="password">Password</label>
        <input type="password" id="password" name='password' class="form-control" required/>
      </div>
    
      <div class="form-check mb-4">
        <input class="form-check-input" type="checkbox" id="showPasswordCheck" onclick="togglePassword()">
        <label class="form-check-label" for="showPasswordCheck">Show Password</label>
      </div>
    
      <div class="text-center pt-1 mb-3 pb-1">
        <button class="btn btn-custom btn-block fa-lg mb-2" type="submit">Log in</button>
      </div>

  </form>
{% endblock %}
<!-- 
<div class="text-center">
        <a class="text-muted" href="{% url 'users:forgot' %}">Forgot password?</a>
      </div>
    -->

LoyolaHouse/Users/templates/users/myprofile.html
{% extends "dashboard.html" %}

LoyolaHouse/Users/templates/users/register.html
{% extends 'dashboard.html' %}
{% block content %}
<div>
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} text-center">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <form action="{% url 'users:newAccount' %}" method="POST">
        {% csrf_token %}
        <div class="form-outline mb-4">
            <label class="form-label" for="role">User Role</label>
            <select name="role" id="role">
                {% for role in roles %}
                    <option value="{{ role.role_id }}">{{ role.role_desc }}</option>
                {% endfor %}
            </select>
          </div>

          <div class="form-outline mb-4">
            <label class="form-label" for="email">Email</label>
            <input type="email" id="email" name="email" class="form-control" placeholder="Email Address" required/>
          </div>
    
          <div class="form-outline mb-4">
            <label class="form-label" for="FName">First Name</label>
            <input type="text" id="FName" name="FName" class="form-control" required/>
          </div>
        
          <div class="form-outline mb-4">
            <label class="form-label" for="LName">Last Name</label>
            <input type="text" id="LName" name="LName" class="form-control" required/>
          </div>
    
          <div class="form-outline mb-4">
            <label class="form-label" for="contact">Contact Number</label>
            <input type="tel" class="form-control" name="contact" id="contact" required 
                maxlength="11" minlength="11" value="09" pattern="[0-9]{11}"
                onkeypress="return event.charCode >= 48 && event.charCode <= 57">
          </div>
    
          <div class="form-outline mb-4">
            <label class="form-label" for="password">Password</label>
            <input type="password" id="password" name="password" class="form-control" required/>
          </div>

          <div class="form-outline mb-4">
            <label class="form-label" for="password1">Confirm Password</label>
            <input type="password" id="password1" name="password1" class="form-control" required/>
          </div>

          <div class="text-center pt-1 mb-3 pb-1">
            <button class="btn btn-custom btn-block fa-lg mb-2" type="submit">Register</button>
          </div>
    </form>
</div>
{% endblock %}